apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "yc-product-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "yc-product-service.name" . }}
    environment: {{ .Values.environment_name }}
    costCenter: {{ .Values.cost_center }}
    dns: route53
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | trimSuffix "\n" | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "yc-product-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
