# This is a YAML-formatted file
# Declare variables to be passed into your templates.

environment_name: production
cost_center: yara-connect
replicaCount: 1

image:
    repository: 387984977604.dkr.ecr.eu-west-1.amazonaws.com/yc-product-service
    pullPolicy: IfNotPresent

podAnnotations:
    iam.amazonaws.com/role: yc-product-service-s3-production-role
    vault.security.banzaicloud.io/vault-addr: 'https://vault.prod.robocop.yaradigitallabs.io'
    vault.security.banzaicloud.io/vault-path: 'kubernetes-apac-production'
    vault.security.banzaicloud.io/vault-role: 'yaraconnect-apac-production-role'
    podSecure: 'true'

imagePullSecrets: []

service:
    type: ClusterIP
    port: 8080
    containerPort: 8080
    annotations:
        getambassador.io/config: |
            ---
            apiVersion: ambassador/v1
            kind: Mapping
            name: yc-product-service
            ambassador_id: sh-yaraconnect-global
            prefix: /
            host: yc-product-service.apac.yaradigitallabs.io
            service: yc-product-service-production:8080
            timeout_ms: 30000

resources:
    limits:
        cpu: 1
        memory: 1Gi
    requests:
        cpu: 0.5
        memory: 512Mi

jobs:
    resources:
        limits:
            cpu: 0.5
            memory: 512Mi
        requests:
            cpu: 0.01
            memory: 128Mi

envs:
    DATABASE_CLIENT: postgres
    AWS_DEFAULT_REGION: ap-southeast-1
    NODE_ENV: production
    ENV: production
    DB_PORT: '5432'
    

nodeSelector: {}

tolerations: []

affinity: {}

hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    metrics:
        - resource:
              name: cpu
              target:
                  averageUtilization: 80
                  type: Utilization
          type: Resource
        - resource:
              name: memory
              target:
                  averageUtilization: 80
                  type: Utilization
          type: Resource
